server:
  port: 8082 
  
spring:
  application:
    name: board-service
 
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    generate-ddl: true
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/negomarket?serverTimezone=Asia/Seoul
    username: root
    password: root
      
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true 
    fetch-registry: true 
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka 
      
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans
