server:
  port: 8000
  
spring:
  application:
    name: apigateway-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    
  cloud:
    gateway:
      routes:
      - id: board-service
        uri: lb://BOARD-SERVICE
        predicates:
        - Path=/board-service/**
        - Method=GET, POST, PUT, DELETE
        
      - id: sell-service
        uri: lb://SELL-SERVICE
        predicates:
        - Path=/sell-service/**
        - Method=GET, POST, PUT, DELETE
        
      - id: chat-service
        uri: lb:ws://CHAT-SERVICE/
        predicates:
        - Path=/chat-service/wsstomp
        - Method=GET, POST, PUT, DELETE

      - id: chat-service
        uri: lb://CHAT-SERVICE
        predicates:
        - Path=/chat-service/**  
        - Method=GET, POST, PUT, DELETE
        
       
      - id: imgfile-service 
        uri: lb://IMGFILE-SERVICE 
        predicates:
        - Path=/imgfile-service/**   
        - Method=GET, POST, PUT, DELETE
        
      - id: user-service 
        uri: lb://USER-SERVICE 
        predicates:
        - Path=/user-service/tokenValidation
        - Method=GET
        
      - id: user-service 
        uri: lb://USER-SERVICE 
        predicates:
        - Path=/user-service/pwvalidation
        - Method=POST
        
           
      - id: user-service 
        uri: lb://USER-SERVICE 
        predicates:
        - Path=/user-service/users
        - Method=POST
        
      - id: user-service 
        uri: lb://USER-SERVICE 
        predicates:
        - Path=/user-service/login 
        - Method=POST
        
      - id: user-service 
        uri: lb://USER-SERVICE 
        predicates:
        - Path=/user-service/pic/*
        - Method=GET
        
      - id: user-service 
        uri: lb://USER-SERVICE 
        predicates:
        - Path=/user-service/testinsert
        - Method=POST
      
      - id: user-service 
        uri: lb://USER-SERVICE 
        predicates:
        - Path=/user-service/health_check
        - Method=GET
        
      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user-service/actuator/**
        - Method=GET, POST
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/user-service/(?<segment>.*), /$\{segment}
      

      - id: user-service 
        uri: lb://USER-SERVICE 
        predicates:
        - Path=/user-service/**   
        - Method=GET, POST, PUT, DELETE
        filters:
        - name: AuthorizationFilter
     
      
eureka:
  instance:
    prefer-ip-address: true
    ip-address: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true 
    fetch-registry: true 
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, beans, busrefresh
