name: Board-service Java ci/cd with Maven

on:
  push:
    paths:
      - "spring_Negomarket/board-service/**"
  pull_request:
    paths:
      - "spring_Negomarket/board-service/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: setup jdk11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: cd spring_Negomarket/board-service && mvn clean install -DskipTests=true

      - name: docker image build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/board-service spring_Negomarket/board-service

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: dockerhub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/board-service

  # deploy:
  #   needs: build
  #   name: deploy
  #   runs-on: [self-hosted, label-1]
  #   steps:
  #     - name: login dockerhub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: docker run
  #       run: |
  #         docker stop board-service && docker rm board-service && docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/board-service
  #         docker run -d --name board-service ${{ secrets.DOCKERHUB_USERNAME }}/board-service
