
name: Nego React App

on:
  push:
    paths:
      - "react_Negomarket/**"
  pull_request:
    paths:
      - "react_Negomarket/**"

permissions:
  contents: read

jobs: 
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: setup nodejs
      uses: actions/setup-node@v3
      with:
        java-version: '18.16.0'

    - name: Install Dependencies
      run: cd react_Negomarket/ &&npm install

    - name: Build react app
      run: npm run build
      
    - name: docker image build
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/negomarket .

    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: dockerhub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/negomarket


  deploy:
    needs: build
    name: deploy
    runs-on: [self-hosted, label-1]
    steps:
      - name: login dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker run
        run: |
          docker stop negomarket && docker rm negomarket && docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/negomarket
          docker run -d --name negomarket ${{ secrets.DOCKERHUB_USERNAME }}/negomarket
